name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "$" > "$HOME/.ssh/key2"
      - run: chmod 600 "$HOME/.ssh/key2"
      # Deploy
      - run: rsync -e "ssh -p 20022 -i $HOME/.ssh/key2 -o StrictHostKeyChecking=no" --archive --compress --delete . cr14678.timeweb.ru:/home/c/cr14678/django/
